[profile.default]
solc = "0.8.15"
bytecode_hash = "none"
optimizer_runs = 1000000
fs_permissions = [{ access = "read-write", path = "./addresses.json"}]
[profile.intense.fuzz]
runs = 10000

[rpc_endpoints]
gnosis = "${GNOSIS_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"